/**
 * Granular permission constants for frontend authorization.
 * Strictly mirrors the backend `src/constants/permissions.js` source of truth.
 */
export const PERMISSIONS = Object.freeze({
  // Schools
  SCHOOLS_READ: 'schools:read',
  SCHOOLS_CREATE: 'schools:create',
  SCHOOLS_UPDATE: 'schools:update',
  SCHOOLS_DELETE: 'schools:delete',
  SCHOOLS_MANAGE: 'schools:manage',

  // Users
  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',

  // Students
  STUDENTS_READ: 'students:read',
  STUDENTS_CREATE: 'students:create',
  STUDENTS_UPDATE: 'students:update',
  STUDENTS_DELETE: 'students:delete',
  STUDENTS_MANAGE: 'students:manage',

  // Teachers
  TEACHERS_READ: 'teachers:read',
  TEACHERS_CREATE: 'teachers:create',
  TEACHERS_UPDATE: 'teachers:update',
  TEACHERS_DELETE: 'teachers:delete',
  TEACHERS_MANAGE: 'teachers:manage',

  // Parents
  PARENTS_READ: 'parents:read',
  PARENTS_CREATE: 'parents:create',
  PARENTS_UPDATE: 'parents:update',
  PARENTS_DELETE: 'parents:delete',

  // Academic Sessions
  ACADEMIC_SESSIONS_READ: 'academic_sessions:read',
  ACADEMIC_SESSIONS_CREATE: 'academic_sessions:create',
  ACADEMIC_SESSIONS_UPDATE: 'academic_sessions:update',
  ACADEMIC_SESSIONS_DELETE: 'academic_sessions:delete',
  ACADEMIC_SESSIONS_MANAGE: 'academic_sessions:manage',

  // Student Promotions
  PROMOTIONS_READ: 'promotions:read',
  PROMOTIONS_CREATE: 'promotions:create',
  PROMOTIONS_MANAGE: 'promotions:manage',

  // Classes
  CLASSES_READ: 'classes:read',
  CLASSES_CREATE: 'classes:create',
  CLASSES_UPDATE: 'classes:update',
  CLASSES_DELETE: 'classes:delete',

  // Sections
  SECTIONS_READ: 'sections:read',
  SECTIONS_CREATE: 'sections:create',
  SECTIONS_UPDATE: 'sections:update',
  SECTIONS_DELETE: 'sections:delete',

  // Subjects
  SUBJECTS_READ: 'subjects:read',
  SUBJECTS_CREATE: 'subjects:create',
  SUBJECTS_UPDATE: 'subjects:update',
  SUBJECTS_DELETE: 'subjects:delete',

  // Attendance
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_CREATE: 'attendance:create',
  ATTENDANCE_UPDATE: 'attendance:update',
  ATTENDANCE_DELETE: 'attendance:delete',
  ATTENDANCE_MANAGE: 'attendance:manage',
  ATTENDANCE_REPORT: 'attendance:report',

  // Leaves
  LEAVES_READ: 'leaves:read',
  LEAVES_CREATE: 'leaves:create',
  LEAVES_UPDATE: 'leaves:update',
  LEAVES_DELETE: 'leaves:delete',
  LEAVES_APPROVE: 'leaves:approve',
  LEAVES_REJECT: 'leaves:reject',
  LEAVES_MANAGE: 'leaves:manage',

  // Timetable
  TIMETABLE_READ: 'timetable:read',
  TIMETABLE_CREATE: 'timetable:create',
  TIMETABLE_UPDATE: 'timetable:update',
  TIMETABLE_DELETE: 'timetable:delete',

  // Assignments
  ASSIGNMENTS_READ: 'assignments:read',
  ASSIGNMENTS_CREATE: 'assignments:create',
  ASSIGNMENTS_UPDATE: 'assignments:update',
  ASSIGNMENTS_DELETE: 'assignments:delete',
  ASSIGNMENTS_GRADE: 'assignments:grade',

  // Quizzes
  QUIZZES_READ: 'quizzes:read',
  QUIZZES_CREATE: 'quizzes:create',
  QUIZZES_UPDATE: 'quizzes:update',
  QUIZZES_DELETE: 'quizzes:delete',
  QUIZZES_GRADE: 'quizzes:grade',

  // Exams
  EXAMS_READ: 'exams:read',
  EXAMS_CREATE: 'exams:create',
  EXAMS_UPDATE: 'exams:update',
  EXAMS_DELETE: 'exams:delete',
  EXAMS_PUBLISH: 'exams:publish',

  // Results
  RESULTS_READ: 'results:read',
  RESULTS_CREATE: 'results:create',
  RESULTS_UPDATE: 'results:update',
  RESULTS_PUBLISH: 'results:publish',
  RESULTS_LOCK: 'results:lock',

  // Fees
  FEES_READ: 'fees:read',
  FEES_CREATE: 'fees:create',
  FEES_UPDATE: 'fees:update',
  FEES_DELETE: 'fees:delete',
  FEES_MANAGE: 'fees:manage',

  // Payments
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_CREATE: 'payments:create',

  // Notices
  NOTICES_READ: 'notices:read',
  NOTICES_CREATE: 'notices:create',
  NOTICES_UPDATE: 'notices:update',
  NOTICES_PUBLISH: 'notices:publish',
  NOTICES_DELETE: 'notices:delete',

  // Notifications
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_MANAGE: 'notifications:manage',

  // Messages
  MESSAGES_READ: 'messages:read',
  MESSAGES_CREATE: 'messages:create',
  MESSAGES_MANAGE: 'messages:manage',

  // Library
  LIBRARY_READ: 'library:read',
  LIBRARY_CREATE: 'library:create',
  LIBRARY_UPDATE: 'library:update',
  LIBRARY_ISSUE: 'library:issue',
  LIBRARY_RETURN: 'library:return',

  // Certificates
  CERTIFICATES_READ: 'certificates:read',
  CERTIFICATES_CREATE: 'certificates:create',
  CERTIFICATES_MANAGE: 'certificates:manage',

  // Reports
  REPORTS_READ: 'reports:read',
  REPORTS_GENERATE: 'reports:generate',

  // Audit Logs
  AUDIT_LOGS_READ: 'audit_logs:read',

  // AI
  AI_USE: 'ai:use',
  AI_MANAGE: 'ai:manage',

  // Subscriptions
  SUBSCRIPTIONS_READ: 'subscriptions:read',
  SUBSCRIPTIONS_MANAGE: 'subscriptions:manage',
});

export const PERMISSION_VALUES = Object.freeze(Object.values(PERMISSIONS));
export const PERMISSION_SET = Object.freeze(new Set(PERMISSION_VALUES));

/**
 * Default role-to-permission mappings.
 * SUPER_ADMIN has implicit access to all permissions.
 */
export const DEFAULT_ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: PERMISSION_VALUES,

  SCHOOL_ADMIN: [
    PERMISSIONS.SCHOOLS_READ,
    PERMISSIONS.SCHOOLS_UPDATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.STUDENTS_DELETE,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.TEACHERS_CREATE,
    PERMISSIONS.TEACHERS_UPDATE,
    PERMISSIONS.TEACHERS_DELETE,
    PERMISSIONS.TEACHERS_MANAGE,
    PERMISSIONS.PARENTS_READ,
    PERMISSIONS.PARENTS_CREATE,
    PERMISSIONS.PARENTS_UPDATE,
    PERMISSIONS.PARENTS_DELETE,
    PERMISSIONS.ACADEMIC_SESSIONS_READ,
    PERMISSIONS.ACADEMIC_SESSIONS_CREATE,
    PERMISSIONS.ACADEMIC_SESSIONS_UPDATE,
    PERMISSIONS.ACADEMIC_SESSIONS_DELETE,
    PERMISSIONS.ACADEMIC_SESSIONS_MANAGE,
    PERMISSIONS.PROMOTIONS_READ,
    PERMISSIONS.PROMOTIONS_CREATE,
    PERMISSIONS.PROMOTIONS_MANAGE,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.CLASSES_CREATE,
    PERMISSIONS.CLASSES_UPDATE,
    PERMISSIONS.CLASSES_DELETE,
    PERMISSIONS.SECTIONS_READ,
    PERMISSIONS.SECTIONS_CREATE,
    PERMISSIONS.SECTIONS_UPDATE,
    PERMISSIONS.SECTIONS_DELETE,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.SUBJECTS_CREATE,
    PERMISSIONS.SUBJECTS_UPDATE,
    PERMISSIONS.SUBJECTS_DELETE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ATTENDANCE_DELETE,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_REPORT,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_CREATE,
    PERMISSIONS.LEAVES_UPDATE,
    PERMISSIONS.LEAVES_DELETE,
    PERMISSIONS.LEAVES_APPROVE,
    PERMISSIONS.LEAVES_REJECT,
    PERMISSIONS.LEAVES_MANAGE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.TIMETABLE_CREATE,
    PERMISSIONS.TIMETABLE_UPDATE,
    PERMISSIONS.TIMETABLE_DELETE,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_CREATE,
    PERMISSIONS.ASSIGNMENTS_UPDATE,
    PERMISSIONS.ASSIGNMENTS_DELETE,
    PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.QUIZZES_READ,
    PERMISSIONS.QUIZZES_CREATE,
    PERMISSIONS.QUIZZES_UPDATE,
    PERMISSIONS.QUIZZES_DELETE,
    PERMISSIONS.QUIZZES_GRADE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.EXAMS_CREATE,
    PERMISSIONS.EXAMS_UPDATE,
    PERMISSIONS.EXAMS_DELETE,
    PERMISSIONS.EXAMS_PUBLISH,
    PERMISSIONS.RESULTS_READ,
    PERMISSIONS.RESULTS_CREATE,
    PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.RESULTS_PUBLISH,
    PERMISSIONS.RESULTS_LOCK,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_UPDATE,
    PERMISSIONS.FEES_DELETE,
    PERMISSIONS.FEES_MANAGE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.NOTICES_READ,
    PERMISSIONS.NOTICES_CREATE,
    PERMISSIONS.NOTICES_UPDATE,
    PERMISSIONS.NOTICES_PUBLISH,
    PERMISSIONS.NOTICES_DELETE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_CREATE,
    PERMISSIONS.MESSAGES_MANAGE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_CREATE,
    PERMISSIONS.LIBRARY_UPDATE,
    PERMISSIONS.LIBRARY_ISSUE,
    PERMISSIONS.LIBRARY_RETURN,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.CERTIFICATES_CREATE,
    PERMISSIONS.CERTIFICATES_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.AUDIT_LOGS_READ,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_MANAGE,
  ],

  TEACHER: [
    PERMISSIONS.ACADEMIC_SESSIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.SECTIONS_READ,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ATTENDANCE_REPORT,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_CREATE,
    PERMISSIONS.LEAVES_UPDATE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_CREATE,
    PERMISSIONS.ASSIGNMENTS_UPDATE,
    PERMISSIONS.ASSIGNMENTS_DELETE,
    PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.QUIZZES_READ,
    PERMISSIONS.QUIZZES_CREATE,
    PERMISSIONS.QUIZZES_UPDATE,
    PERMISSIONS.QUIZZES_DELETE,
    PERMISSIONS.QUIZZES_GRADE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.RESULTS_READ,
    PERMISSIONS.RESULTS_CREATE,
    PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.NOTICES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_CREATE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.AI_USE,
  ],

  STUDENT: [
    PERMISSIONS.ACADEMIC_SESSIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.SECTIONS_READ,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_CREATE,
    PERMISSIONS.LEAVES_UPDATE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.QUIZZES_READ,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.RESULTS_READ,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.NOTICES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_CREATE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.AI_USE,
  ],

  PARENT: [
    PERMISSIONS.ACADEMIC_SESSIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.QUIZZES_READ,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.RESULTS_READ,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.NOTICES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_CREATE,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.TIMETABLE_READ,
  ],

  ACCOUNTANT: [
    PERMISSIONS.ACADEMIC_SESSIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.FEES_READ,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_UPDATE,
    PERMISSIONS.FEES_DELETE,
    PERMISSIONS.FEES_MANAGE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.NOTICES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.CERTIFICATES_READ,
  ],

  LIBRARIAN: [
    PERMISSIONS.ACADEMIC_SESSIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_CREATE,
    PERMISSIONS.LIBRARY_UPDATE,
    PERMISSIONS.LIBRARY_ISSUE,
    PERMISSIONS.LIBRARY_RETURN,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.NOTICES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.MESSAGES_READ,
  ],

  STAFF: [
    PERMISSIONS.ACADEMIC_SESSIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.NOTICES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_CREATE,
  ],
});
