/**
 * Authentication and provisioning event constants for audit logging.
 * Used to categorize events consistently across the platform.
 */
export const AUTH_EVENTS = Object.freeze({
  // Authentication events
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REFRESH_TOKEN_ROTATED: 'REFRESH_TOKEN_ROTATED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  EMAIL_VERIFICATION_REQUESTED: 'EMAIL_VERIFICATION_REQUESTED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',

  // Provisioning & Lifecycle events
  SUPER_ADMIN_SEEDED: 'SUPER_ADMIN_SEEDED',
  SCHOOL_CREATED: 'SCHOOL_CREATED',
  SCHOOL_UPDATED: 'SCHOOL_UPDATED',
  SCHOOL_ACTIVATED: 'SCHOOL_ACTIVATED',
  SCHOOL_SUSPENDED: 'SCHOOL_SUSPENDED',
  SCHOOL_REACTIVATED: 'SCHOOL_REACTIVATED',
  SCHOOL_EXPIRED: 'SCHOOL_EXPIRED',
  SCHOOL_STATUS_CHANGED: 'SCHOOL_STATUS_CHANGED',
  SCHOOL_ADMIN_INVITED: 'SCHOOL_ADMIN_INVITED',
  SCHOOL_ADMIN_ACTIVATED: 'SCHOOL_ADMIN_ACTIVATED',
  PROVISIONING_FAILED: 'PROVISIONING_FAILED',

  // Academic events
  ACADEMIC_SESSION_CREATED: 'ACADEMIC_SESSION_CREATED',
  ACADEMIC_SESSION_UPDATED: 'ACADEMIC_SESSION_UPDATED',
  ACADEMIC_SESSION_DELETED: 'ACADEMIC_SESSION_DELETED',
  ACADEMIC_SESSION_STATUS_CHANGED: 'ACADEMIC_SESSION_STATUS_CHANGED',
  CLASS_CREATED: 'CLASS_CREATED',
  CLASS_UPDATED: 'CLASS_UPDATED',
  CLASS_DELETED: 'CLASS_DELETED',
  SECTION_CREATED: 'SECTION_CREATED',
  SECTION_UPDATED: 'SECTION_UPDATED',
  SECTION_DELETED: 'SECTION_DELETED',
  SUBJECT_CREATED: 'SUBJECT_CREATED',
  SUBJECT_UPDATED: 'SUBJECT_UPDATED',
  SUBJECT_DELETED: 'SUBJECT_DELETED',
  STUDENT_CREATED: 'STUDENT_CREATED',
  STUDENT_UPDATED: 'STUDENT_UPDATED',
  STUDENT_DELETED: 'STUDENT_DELETED',
  TEACHER_CREATED: 'TEACHER_CREATED',
  TEACHER_INVITED: 'TEACHER_INVITED',
  TEACHER_ACTIVATED: 'TEACHER_ACTIVATED',
  TEACHER_UPDATED: 'TEACHER_UPDATED',
  TEACHER_DELETED: 'TEACHER_DELETED',
  PARENT_CREATED: 'PARENT_CREATED',
  PARENT_UPDATED: 'PARENT_UPDATED',
  PARENT_DELETED: 'PARENT_DELETED',
  ENROLLMENT_CREATED: 'ENROLLMENT_CREATED',
  ENROLLMENT_UPDATED: 'ENROLLMENT_UPDATED',
  ENROLLMENT_DELETED: 'ENROLLMENT_DELETED',
  STUDENT_PARENT_LINKED: 'STUDENT_PARENT_LINKED',
  STUDENT_PARENT_UNLINKED: 'STUDENT_PARENT_UNLINKED',
  STUDENT_PARENT_UPDATED: 'STUDENT_PARENT_UPDATED',
  TEACHER_ASSIGNMENT_CREATED: 'TEACHER_ASSIGNMENT_CREATED',
  TEACHER_ASSIGNMENT_UPDATED: 'TEACHER_ASSIGNMENT_UPDATED',
  TEACHER_ASSIGNMENT_DELETED: 'TEACHER_ASSIGNMENT_DELETED',
  STUDENT_PROMOTED: 'STUDENT_PROMOTED',
  STUDENT_RETAINED: 'STUDENT_RETAINED',
  STUDENT_GRADUATED: 'STUDENT_GRADUATED',
  STUDENT_TRANSFERRED: 'STUDENT_TRANSFERRED',
  BULK_STUDENT_PROMOTION: 'BULK_STUDENT_PROMOTION',

  // Attendance events
  ATTENDANCE_CREATED: 'ATTENDANCE_CREATED',
  ATTENDANCE_UPDATED: 'ATTENDANCE_UPDATED',
  ATTENDANCE_DELETED: 'ATTENDANCE_DELETED',
  ATTENDANCE_BULK_MARKED: 'ATTENDANCE_BULK_MARKED',
  ATTENDANCE_CORRECTED: 'ATTENDANCE_CORRECTED',
  ATTENDANCE_EXPORTED: 'ATTENDANCE_EXPORTED',

  // Leave events
  LEAVE_CREATED: 'LEAVE_CREATED',
  LEAVE_UPDATED: 'LEAVE_UPDATED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_DELETED: 'LEAVE_DELETED',

  // Timetable events
  TIMETABLE_CREATED: 'TIMETABLE_CREATED',
  TIMETABLE_UPDATED: 'TIMETABLE_UPDATED',
  TIMETABLE_DELETED: 'TIMETABLE_DELETED',

  // Assignment events
  ASSIGNMENT_CREATED: 'ASSIGNMENT_CREATED',
  ASSIGNMENT_UPDATED: 'ASSIGNMENT_UPDATED',
  ASSIGNMENT_DELETED: 'ASSIGNMENT_DELETED',
  ASSIGNMENT_PUBLISHED: 'ASSIGNMENT_PUBLISHED',
  ASSIGNMENT_SUBMITTED: 'ASSIGNMENT_SUBMITTED',
  ASSIGNMENT_GRADED: 'ASSIGNMENT_GRADED',

  // Quiz events
  QUIZ_CREATED: 'QUIZ_CREATED',
  QUIZ_UPDATED: 'QUIZ_UPDATED',
  QUIZ_DELETED: 'QUIZ_DELETED',
  QUIZ_PUBLISHED: 'QUIZ_PUBLISHED',
  QUIZ_ATTEMPT_STARTED: 'QUIZ_ATTEMPT_STARTED',
  QUIZ_ATTEMPT_SUBMITTED: 'QUIZ_ATTEMPT_SUBMITTED',
  QUIZ_ATTEMPT_GRADED: 'QUIZ_ATTEMPT_GRADED',

  // Exam events
  EXAM_CREATED: 'EXAM_CREATED',
  EXAM_UPDATED: 'EXAM_UPDATED',
  EXAM_DELETED: 'EXAM_DELETED',
  EXAM_PUBLISHED: 'EXAM_PUBLISHED',
  EXAM_PAPER_CREATED: 'EXAM_PAPER_CREATED',
  EXAM_PAPER_UPDATED: 'EXAM_PAPER_UPDATED',
  EXAM_PAPER_DELETED: 'EXAM_PAPER_DELETED',

  // Result events
  GRADING_SCALE_CREATED: 'GRADING_SCALE_CREATED',
  GRADING_SCALE_UPDATED: 'GRADING_SCALE_UPDATED',
  GRADING_SCALE_DELETED: 'GRADING_SCALE_DELETED',
  RESULT_CREATED: 'RESULT_CREATED',
  RESULT_UPDATED: 'RESULT_UPDATED',
  RESULT_LOCKED: 'RESULT_LOCKED',
  RESULT_UNLOCKED: 'RESULT_UNLOCKED',
  RESULT_PUBLISHED: 'RESULT_PUBLISHED',

  // Fee & Financial events
  FEE_CATEGORY_CREATED: 'FEE_CATEGORY_CREATED',
  FEE_CATEGORY_UPDATED: 'FEE_CATEGORY_UPDATED',
  FEE_CATEGORY_DELETED: 'FEE_CATEGORY_DELETED',
  FEE_STRUCTURE_CREATED: 'FEE_STRUCTURE_CREATED',
  FEE_STRUCTURE_UPDATED: 'FEE_STRUCTURE_UPDATED',
  FEE_STRUCTURE_DELETED: 'FEE_STRUCTURE_DELETED',
  FEE_CONCESSION_CREATED: 'FEE_CONCESSION_CREATED',
  FEE_CONCESSION_UPDATED: 'FEE_CONCESSION_UPDATED',
  FEE_CONCESSION_DELETED: 'FEE_CONCESSION_DELETED',
  FEE_INVOICE_GENERATED: 'FEE_INVOICE_GENERATED',
  FEE_INVOICE_UPDATED: 'FEE_INVOICE_UPDATED',
  FEE_INVOICE_CANCELLED: 'FEE_INVOICE_CANCELLED',
  FEE_PAYMENT_RECORDED: 'FEE_PAYMENT_RECORDED',
  FEE_PAYMENT_REVERSED: 'FEE_PAYMENT_REVERSED',

  // Notice events
  NOTICE_CREATED: 'NOTICE_CREATED',
  NOTICE_UPDATED: 'NOTICE_UPDATED',
  NOTICE_DELETED: 'NOTICE_DELETED',
  NOTICE_PUBLISHED: 'NOTICE_PUBLISHED',

  // Notification events
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_READ: 'NOTIFICATION_READ',

  // Messaging events
  CONVERSATION_CREATED: 'CONVERSATION_CREATED',
  MESSAGE_SENT: 'MESSAGE_SENT',
});

/**
 * Token type identifiers for JWT claims.
 */
export const TOKEN_TYPES = Object.freeze({
  ACCESS: 'access',
  REFRESH: 'refresh',
});
